window.TRADINGAGENTS_CONFIG = {
    apiBaseUrl: "https://apicrypto.nguyenchitrai.id.vn",
    // apiBaseUrl: "http://103.77.242.137:8001",
    // apiBaseUrl: "http://localhost:8000",
    provider: "minimax",
    defaultModel: "MiniMax-M2.7",
    analysisDefaults: {
        symbol: "BTC-USDT",
        assetType: "crypto",
        analysisDate: "",
        lookbackDays: 7,
        outputLanguage: "Vietnamese",
        selectedAnalysts: ["market", "social", "news", "fundamentals"],
        researchDepth: "quick",
        model: "MiniMax-M2.7",
        checkpointEnabled: false,
    },
    analysisOptions: {
        lookbackPresets: [
            { value: "7", label: "7 days", days: 7 },
            { value: "14", label: "14 days", days: 14 },
            { value: "30", label: "30 days", days: 30 },
            { value: "90", label: "90 days", days: 90 },
        ],
        outputLanguages: [
            "Vietnamese",
            "English",
            "Chinese",
            "Japanese",
            "Korean",
            "Hindi",
            "Spanish",
            "Portuguese",
            "French",
            "German",
            "Arabic",
            "Russian",
        ],
        analysts: [
            { value: "market", label: "Market Analyst" },
            { value: "social", label: "Sentiment Analyst" },
            { value: "news", label: "News Analyst" },
            { value: "fundamentals", label: "Fundamentals Analyst" },
        ],
        researchDepths: [
            { value: "quick", label: "Quick", rounds: 1, description: "Fast scan with minimal debate." },
            { value: "medium", label: "Medium", rounds: 3, description: "Balanced research depth for regular analysis." },
            { value: "deep", label: "Deep", rounds: 5, description: "More debate rounds before the final decision." },
        ],
    },
};
