window.TRADINGAGENTS_CONFIG = {
    apiBaseUrl: "https://apicrypto.nguyenchitrai.id.vn",
    // apiBaseUrl: "http://localhost:8000",
    provider: "minimax",
    defaultModel: "deepseek-v4-flash",
    app: {
        pages: ["agent", "history", "chart", "admin", "chat"],
        defaultPage: "agent",
        coreAnalysts: ["market", "onchain", "social", "news"],
        traceDisplayLimit: 50,
        logDisplayLimit: 50,
        executionLogDisplayLimit: 80,
        minStopDelayMs: 5000,
    },
    auth: {
        storageKey: "tradingagents.googleAuth",
        requireLoginForHistory: true,
    },
    history: {
        pageSize: 20,
        requireLogin: true,
    },
    tradingView: {
        symbol: "BINANCE:BTCUSDT",
        interval: "60",
        symbols: ["BINANCE:BTCUSDT", "BINANCE:ETHUSDT", "BINANCE:SOLUSDT", "BINANCE:XRPUSDT"],
        symbolsStorageKey: "tradingagents.chartSymbols",
    },
    analysisDefaults: {
        // FE form defaults live here; backend /api/config should not override them.
        symbol: "BTC-USDT",
        assetType: "crypto",
        analysisDate: "",
        lookbackDays: 14,
        outputLanguage: "vietnamese",
        selectedAnalysts: ["market", "onchain", "social", "news"],
        researchDepth: "auto",
        model: "deepseek-v4-flash",
        reasoningEffort: "max",
        checkpointEnabled: false,
    },
    analysisOptions: {
        lookbackPresets: [
            { value: "7", label: "7 days", days: 7 },
            { value: "14", label: "14 days", days: 14 },
            { value: "30", label: "30 days", days: 30 },
            { value: "90", label: "90 days", days: 90 },
        ],
        outputLanguages: [
            "Vietnamese",
            "English",
            "Chinese",
            "Japanese",
            "Korean",
            "Hindi",
            "Spanish",
            "Portuguese",
            "French",
            "German",
            "Arabic",
            "Russian",
        ],
        models: [
            { value: "MiniMax-M2.5", label: "MiniMax M2.5" },
            { value: "MiniMax-M2.7", label: "MiniMax M2.7" },
            { value: "deepseek-v4-flash", label: "DeepSeek V4 Flash" },
            { value: "deepseek-v4-pro", label: "DeepSeek V4 Pro" },
        ],
        reasoningEfforts: [
            { value: "low", label: "low" },
            { value: "medium", label: "medium" },
            { value: "high", label: "high" },
            { value: "xhigh", label: "xhigh" },
            { value: "max", label: "max" },
        ],
        analysts: [
            { value: "market", label: "Market Analyst" },
            { value: "onchain", label: "Onchain Analyst" },
            { value: "social", label: "Social Analyst" },
            { value: "news", label: "News Analyst" },
        ],
        researchDepths: [
            { value: "auto", label: "Auto", rounds: 3, effective_depth: "medium", description: "Backend-managed baseline with future evidence-driven escalation." },
            { value: "quick", label: "Quick", rounds: 1, description: "Fast scan with minimal debate." },
            { value: "medium", label: "Medium", rounds: 3, description: "Balanced research depth for regular analysis." },
            { value: "deep", label: "Deep", rounds: 5, description: "More debate rounds before the final decision." },
        ],
    },
};
