import re

STATE_UPDATE_KEYS = {
    "messages",
    "company_of_interest",
    "asset_type",
    "trade_date",
    "past_context",
    "sender",
    "investment_debate_state",
    "risk_debate_state",
    "market_report",
    "market_source_bundle",
    "onchain_report",
    "onchain_endpoint_analyses",
    "onchain_analysis_structured",
    "coinglass_endpoint_results",
    "sentiment_report",
    "news_report",
    "evidence_items",
    "endpoint_summaries",
    "final_trade_decision",
    "final_trade_decision_structured",
    "verification_report",
    "verification_report_structured",
}

CHAT_WEB_SEARCH_HINT_TERMS = (
    "latest",
    "current",
    "today",
    "recent",
    "newest",
    "live",
    "real time",
    "real-time",
    "market data",
    "price",
    "pricing",
    "quote",
    "news",
    "headline",
    "earnings",
    "filing",
    "10-k",
    "10q",
    "investor relations",
    "guidance",
    "macro",
    "cpi",
    "fomc",
    "source",
    "sources",
    "citation",
    "citations",
    "cite",
    "reference",
    "references",
    "verify",
    "verification",
    "cross-check",
    "fact-check",
    "search",
    "web",
    "internet",
    "browse",
    "lookup",
    "look up",
    "website",
    "mcp",
    "web_search",
    "moi nhat",
    "mới nhất",
    "hom nay",
    "hôm nay",
    "hien tai",
    "hiện tại",
    "thoi gian thuc",
    "thời gian thực",
    "gia",
    "giá",
    "tin tuc",
    "tin tức",
    "tim kiem",
    "tìm kiếm",
    "tra cuu",
    "tra cứu",
    "nguon",
    "nguồn",
    "tham chieu",
    "tham chiếu",
    "xac minh",
    "xác minh",
    "kiem chung",
    "kiểm chứng",
    "kiem tra",
    "kiểm tra",
)

CHAT_IMAGE_HINT_TERMS = (
    "image",
    "screenshot",
    "photo",
    "picture",
    "chart",
    "graph",
    "candlestick",
    "heatmap",
    "visual",
    "understand_image",
    "anh",
    "ảnh",
    "hinh",
    "hình",
    "bieu do",
    "biểu đồ",
    "do thi",
    "đồ thị",
)

CHAT_URL_PATTERN = re.compile(r"https?://\S+", re.IGNORECASE)
