from __future__ import annotations

import json
import re
from typing import Any


EVIDENCE_BLOCK_TAG = "structured_evidence"
_EVIDENCE_BLOCK_RE = re.compile(
    rf"\s*<{EVIDENCE_BLOCK_TAG}>\s*(?P<payload>.*?)\s*</{EVIDENCE_BLOCK_TAG}>\s*",
    re.IGNORECASE | re.DOTALL,
)

_VALID_DIRECTIONS = {"bullish", "bearish", "neutral", "mixed", "unknown"}
_VALID_FRESHNESS = {"realtime", "recent", "stale", "historical", "unknown"}


def get_structured_evidence_instruction(agent_key: str) -> str:
    """Prompt instruction for analyst reports to expose auditable evidence."""
    return (
        f" At the very end of your final answer, append exactly one <{EVIDENCE_BLOCK_TAG}>"
        f"</{EVIDENCE_BLOCK_TAG}> block. The block must be valid JSON and must not be wrapped"
        " in Markdown. Use this exact shape: "
        '{"evidence_items":[{"claim":"...","source":"...","source_type":"ohlcv|indicator|news|social|web|flow|other",'
        '"timestamp":"YYYY-MM-DD or ISO datetime","metric":"...","value":"...","direction":"bullish|bearish|neutral|mixed|unknown",'
        '"confidence":0.0,"freshness":"realtime|recent|stale|historical|unknown","notes":"..."}]}. '
        f"Set agent='{agent_key}' implicitly by writing evidence for this analyst only. Include up to 12"
        " high-signal items. Every item must be directly supported by a tool result, web result,"
        " or prefetched source in this run. Do not invent URLs, timestamps, metrics, or values."
        " If evidence is incomplete or source quality is weak, lower confidence and say why in notes."
        " Keep JSON keys in English even when the report language is not English."
    )


def split_report_and_evidence(
    report: str,
    *,
    agent_key: str,
    agent_label: str,
    report_section: str,
    analysis_date: str,
) -> tuple[str, list[dict[str, Any]]]:
    """Strip the machine evidence block from a report and return normalized items.

    If the model omits the block, return a low-confidence fallback item so the
    verifier can distinguish auditable reports from prose-only reports.
    """
    raw_report = str(report or "")
    payloads = [match.group("payload") for match in _EVIDENCE_BLOCK_RE.finditer(raw_report)]
    clean_report = _EVIDENCE_BLOCK_RE.sub("\n", raw_report).strip()

    evidence_items: list[dict[str, Any]] = []
    for payload in payloads:
        parsed = _load_evidence_payload(payload)
        evidence_items.extend(
            _normalize_evidence_items(
                parsed,
                agent_key=agent_key,
                agent_label=agent_label,
                report_section=report_section,
                analysis_date=analysis_date,
            )
        )

    if not evidence_items and clean_report:
        evidence_items.append(
            {
                "agent": agent_key,
                "agent_label": agent_label,
                "report_section": report_section,
                "claim": "Analyst report was produced without a machine-readable evidence block.",
                "source": "analyst_report",
                "source_type": "other",
                "timestamp": analysis_date,
                "metric": "structured_evidence_presence",
                "value": "missing",
                "direction": "unknown",
                "confidence": 0.2,
                "freshness": "unknown",
                "notes": (
                    "Fallback evidence item generated by the backend; verifier should treat "
                    "this report as weakly auditable."
                ),
            }
        )

    return clean_report, evidence_items


def format_evidence_ledger(items: list[dict[str, Any]] | None, limit: int = 16) -> str:
    """Render compact structured evidence for downstream prompts."""
    evidence_items = [item for item in (items or []) if isinstance(item, dict)]
    if not evidence_items:
        return "<structured evidence ledger unavailable>"

    lines: list[str] = []
    for item in evidence_items[: max(1, limit)]:
        agent = _clean_text(item.get("agent_label") or item.get("agent") or "Analyst", 40)
        source = _clean_text(item.get("source") or "unknown source", 80)
        metric = _clean_text(item.get("metric") or "signal", 60)
        raw_value = item.get("value")
        value = _clean_text("n/a" if raw_value in (None, "") else raw_value, 80)
        direction = _normalize_choice(item.get("direction"), _VALID_DIRECTIONS, "unknown")
        confidence = _coerce_confidence(item.get("confidence"))
        timestamp = _clean_text(item.get("timestamp") or "unknown time", 40)
        claim = _clean_text(item.get("claim") or "No claim supplied.", 600)
        notes = _clean_text(item.get("notes") or "", 140)
        line = (
            f"- [{agent}] {direction} confidence={confidence:.2f}; "
            f"{metric}={value}; time={timestamp}; source={source}; claim={claim}"
        )
        if notes:
            line += f"; notes={notes}"
        lines.append(line)

    if len(evidence_items) > limit:
        lines.append(f"- ... {len(evidence_items) - limit} more evidence item(s) omitted from prompt context.")

    return "\n".join(lines)


def evidence_items_to_markdown(items: list[dict[str, Any]] | None) -> str:
    evidence_items = [item for item in (items or []) if isinstance(item, dict)]
    if not evidence_items:
        return ""

    rows = [
        "| Agent | Direction | Confidence | Metric | Value | Timestamp | Source | Claim |",
        "| --- | --- | ---: | --- | --- | --- | --- | --- |",
    ]
    for item in evidence_items:
        rows.append(
            "| "
            + " | ".join(
                _md_cell(value)
                for value in (
                    item.get("agent_label") or item.get("agent") or "",
                    item.get("direction") or "",
                    f"{_coerce_confidence(item.get('confidence')):.2f}",
                    item.get("metric") or "",
                    item.get("value") or "",
                    item.get("timestamp") or "",
                    item.get("source") or "",
                    item.get("claim") or "",
                )
            )
            + " |"
        )
    return "\n".join(rows)


def _load_evidence_payload(payload: str) -> list[dict[str, Any]]:
    try:
        parsed = json.loads(str(payload or "").strip())
    except json.JSONDecodeError:
        return []

    if isinstance(parsed, list):
        return [item for item in parsed if isinstance(item, dict)]
    if isinstance(parsed, dict):
        candidates = parsed.get("evidence_items")
        if candidates is None:
            candidates = parsed.get("items")
        if isinstance(candidates, list):
            return [item for item in candidates if isinstance(item, dict)]
    return []


def _normalize_evidence_items(
    items: list[dict[str, Any]],
    *,
    agent_key: str,
    agent_label: str,
    report_section: str,
    analysis_date: str,
) -> list[dict[str, Any]]:
    normalized: list[dict[str, Any]] = []
    for item in items[:12]:
        claim = _clean_text(item.get("claim"), 1000)
        if not claim:
            continue

        normalized.append(
            {
                "agent": agent_key,
                "agent_label": agent_label,
                "report_section": report_section,
                "claim": claim,
                "source": _clean_text(item.get("source") or "unknown", 180),
                "source_type": _clean_text(item.get("source_type") or "other", 40),
                "timestamp": _clean_text(item.get("timestamp") or analysis_date, 80),
                "metric": _clean_text(item.get("metric") or "signal", 120),
                "value": _safe_value(item.get("value")),
                "direction": _normalize_choice(item.get("direction"), _VALID_DIRECTIONS, "unknown"),
                "confidence": _coerce_confidence(item.get("confidence")),
                "freshness": _normalize_choice(item.get("freshness"), _VALID_FRESHNESS, "unknown"),
                "notes": _clean_text(item.get("notes") or "", 300),
            }
        )
    return normalized


def _clean_text(value: object, limit: int) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)].rstrip() + "..."


def _safe_value(value: object) -> object:
    if value is None:
        return ""
    if isinstance(value, (int, float, bool)):
        return value
    if isinstance(value, str):
        return _clean_text(value, 220)
    return _clean_text(json.dumps(value, ensure_ascii=False, default=str), 220)


def _coerce_confidence(value: object) -> float:
    try:
        confidence = float(value)
    except (TypeError, ValueError):
        return 0.5
    return max(0.0, min(1.0, confidence))


def _normalize_choice(value: object, valid: set[str], fallback: str) -> str:
    normalized = str(value or "").strip().lower()
    return normalized if normalized in valid else fallback


def _md_cell(value: object) -> str:
    return str(value or "").replace("\r\n", " ").replace("\n", " ").replace("|", "\\|")
